<?php
declare(strict_types = 1);

namespace WsBundle\Repository;

use AppBundle\Repository\AppBaseRepository;
use WsBundle\Entity\ApiKey;

/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends AppBaseRepository
{

    const ALIAS = 'apiKeyStorage';

    /**
     * @param string $apiKey
     *
     * @return ApiKey|null
     */
    public function findByApiKey($apiKey)
    {
        $qb = $this->getDefaultQueryBuilder();
        $qb->andWhere(self::ALIAS . '.apiKey = :apiKey');

        $qb->setParameter('apiKey',$apiKey);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
