
filter:
    excluded_paths:
        - 'src/AppBundle/DataFixtures/*'
        - 'app/*'
        - 'vendor/*'
        - 'tests/*'
        - 'bin/*'
        - 'var/*'
        - 'phing/*'
        - 'web/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            before_keywords:
                catch: false

tools:
    external_code_coverage: true
