<?php

namespace AppBundle\Repository;

/**
 * UserRegistryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRegistryRepository extends \Doctrine\ORM\EntityRepository
{
}
