services:

  # Authentication
  ws.security.api_user_provider:
    class: WsBundle\Security\ApiUserProvider
    arguments:
      - "@app.user.repository"

  ws.security.api_authenticator:
    class: WsBundle\Security\ApiAuthenticator
    public: false
    arguments:
      - "@ws.security_jwt.token_validator"
      - "@ws.security_authenticator.token_request_extractor"
    tags:
      - { name: monolog.logger }

  ws.security_jwt.generator:
    class: WsBundle\Security\Jwt\TokenGenerator
    arguments:
      - "@ws.security.lcobucci.jwt.builder"
      - "@ws.security.lcobucci.jwt.hmac_signer"
      - "%secret%"
      - "%jwt_validation%"

  ws.security_jwt.token_validator:
    class: WsBundle\Security\Jwt\TokenValidator
    arguments:
      - "@ws.security.lcobucci.jwt.validation_data"
      - "@ws.security.lcobucci.jwt.hmac_signer"
      - "%secret%"
      - "%jwt_validation%"

  ws.security_authentication.success_handler:
      class: WsBundle\Security\Authentication\SuccessHandler
      arguments:
        - "@ws.security_jwt.generator"

  ws.security_authentication.failure_handler:
      class: WsBundle\Security\Authentication\FailureHandler

  ## REQUEST PARSING
  ws.security_authenticator.token_request_extractor:
    class: WsBundle\Security\Authenticator\TokenRequestExtractor
    arguments:
      - "@ws.security.lcobucci.jwt.parser"

  ## LIBRARY SERVICES
  ws.security.lcobucci.jwt.builder:
    class: Lcobucci\JWT\Builder

  ws.security.lcobucci.jwt.validation_data:
    class: Lcobucci\JWT\ValidationData

  ws.security.lcobucci.jwt.parser:
    class: Lcobucci\JWT\Parser

  ws.security.lcobucci.jwt.hmac_signer:
    class: Lcobucci\JWT\Signer\Hmac\Sha256

